[package]
name = "avida-verifier"
authors = ["belsy <belsy@nymlab.it>"]
version = "0.1.0"
edition = "2018"

[dependencies]
cw20 = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
cw-storage-plus = { workspace = true }
serde_json = { workspace = true }
ursa = { workspace = true }
thiserror = { workspace = true }
